# Copyright 2026 Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# Authored with assistance from Claude (claude.ai/code).
"""Emit generated/ headers from the Layer records produced by extractors.py:

  kwt_1_arena.h          — sizes + ACT_OFFSET_<slot> macros
  kwt_1_weights.{c,h}    — int8 / int32 / float weight blobs
  kwt_1_params.h         — static const LayerNormParams P_L0_<...> = {...};
                           (one struct constant per Layer in the schedule)
  kwt_1_inference_body.h — sequence of kernel calls referencing
                           ACT_OFFSET_* and P_L<idx>_* symbols
"""

from __future__ import annotations

import pathlib

import torch

from .extractors import (
    AddLayer, DequantOutputLayer, FusedAttentionLayer, GELULayer, Layer,
    LayerNormLayer, LinearLayer, QuantInputLayer, TransposeLayer,
)


def _emit_int8_array(name: str, t: torch.Tensor) -> str:
    flat = t.flatten().to(torch.int8).tolist()
    lines = [f"const int8_t {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), 16):
        chunk = ", ".join(f"0x{b & 0xff:02x}" for b in flat[i : i + 16])
        lines.append(f"  {chunk},")
    lines.append("};\n")
    return "\n".join(lines)


def _emit_int32_array(name: str, t: torch.Tensor) -> str:
    flat = t.flatten().to(torch.int32).tolist()
    lines = [f"const int32_t {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), 8):
        chunk = ", ".join(str(int(v)) for v in flat[i : i + 8])
        lines.append(f"  {chunk},")
    lines.append("};\n")
    return "\n".join(lines)


def _emit_float_array(name: str, t: torch.Tensor) -> str:
    flat = t.flatten().to(torch.float32).tolist()
    lines = [f"const float {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), 6):
        chunk = ", ".join(_float_lit(v) for v in flat[i : i + 6])
        lines.append(f"  {chunk},")
    lines.append("};\n")
    return "\n".join(lines)


def _float_lit(v: float) -> str:
    s = f"{v:.9g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit_weights(out_dir: pathlib.Path, layers: list[Layer]) -> None:
    decls: list[str] = []
    defns: list[str] = []
    for i, layer in enumerate(layers):
        if isinstance(layer, LinearLayer):
            stem = f"L{i}_lin"
            defns.append(_emit_int8_array(f"{stem}_w", layer.weight))
            decls.append(f"extern const int8_t {stem}_w[];")
            defns.append(_emit_int32_array(f"{stem}_ks", layer.kernel_sum))
            decls.append(f"extern const int32_t {stem}_ks[];")
        elif isinstance(layer, LayerNormLayer):
            stem = f"L{i}_ln"
            defns.append(_emit_float_array(f"{stem}_gamma", layer.gamma))
            decls.append(f"extern const float {stem}_gamma[];")
            if layer.beta is not None:
                defns.append(_emit_float_array(f"{stem}_beta", layer.beta))
                decls.append(f"extern const float {stem}_beta[];")
        elif isinstance(layer, GELULayer):
            stem = f"L{i}_gelu"
            defns.append(_emit_int8_array(f"{stem}_lut", layer.lut))
            decls.append(f"extern const int8_t {stem}_lut[];")
    (out_dir / "kwt_1_weights.c").write_text(
        "/* Auto-generated by tools/dump_kwt_1_artifacts.py.  Do not edit. */\n"
        "#include <stdint.h>\n\n" + "\n".join(defns) + "\n"
    )
    (out_dir / "kwt_1_weights.h").write_text(
        "#ifndef KWT_1_WEIGHTS_H_\n#define KWT_1_WEIGHTS_H_\n#include <stdint.h>\n\n"
        + "\n".join(decls) + "\n\n#endif\n"
    )


def emit_params(out_dir: pathlib.Path, layers: list[Layer]) -> None:
    lines: list[str] = [
        "#ifndef KWT_1_PARAMS_H_",
        "#define KWT_1_PARAMS_H_",
        "",
        '#include "kwt_1_layer_params.h"',
        '#include "kwt_1_weights.h"',
        '#include "kwt_1_arena.h"',
        "",
    ]
    for i, layer in enumerate(layers):
        if isinstance(layer, QuantInputLayer):
            lines.append(
                f"static const QuantInputParams P_L{i}_quant = {{\n"
                f"  .num_elements = {layer.num_elements}u,\n"
                f"  .scale = {_float_lit(layer.scale)},\n"
                f"  .zero_point = {layer.zero_point},\n"
                f"  .qmin = {layer.qmin},\n"
                f"  .qmax = {layer.qmax},\n"
                "};")
        elif isinstance(layer, DequantOutputLayer):
            lines.append(
                f"static const DequantOutputParams P_L{i}_dequant = {{\n"
                f"  .num_elements = {layer.num_elements}u,\n"
                f"  .scale = {_float_lit(layer.scale)},\n"
                f"  .zero_point = {layer.zero_point},\n"
                "};")
        elif isinstance(layer, LayerNormLayer):
            stem = f"L{i}_ln"
            beta_ref = f"{stem}_beta" if layer.beta is not None else "(const float*)0"
            lines.append(
                f"static const LayerNormParams P_{stem} = {{\n"
                f"  .num_rows = {layer.num_rows}u,\n"
                f"  .embed_dim = {layer.embed_dim}u,\n"
                f"  .input_zp = {layer.input_zp},\n"
                f"  .input_scale = {_float_lit(layer.input_scale)},\n"
                f"  .output_zp = {layer.output_zp},\n"
                f"  .output_scale = {_float_lit(layer.output_scale)},\n"
                f"  .eps = {_float_lit(layer.eps)},\n"
                f"  .gamma = {stem}_gamma,\n"
                f"  .beta = {beta_ref},\n"
                "};")
        elif isinstance(layer, GELULayer):
            stem = f"L{i}_gelu"
            lines.append(
                f"static const GELUParams P_{stem} = {{\n"
                f"  .num_elements = {layer.num_elements}u,\n"
                f"  .lut = {stem}_lut,\n"
                "};")
        elif isinstance(layer, LinearLayer):
            stem = f"L{i}_lin"
            lines.append(
                f"static const LinearParams P_{stem} = {{\n"
                f"  .num_rows = {layer.num_rows}u,\n"
                f"  .in_features = {layer.in_features}u,\n"
                f"  .out_features = {layer.out_features}u,\n"
                f"  .input_offset = {layer.input_offset},\n"
                f"  .filter_offset = {layer.filter_offset},\n"
                f"  .output_offset = {layer.output_offset},\n"
                f"  .output_multiplier = {layer.output_multiplier},\n"
                f"  .output_shift = {layer.output_shift},\n"
                f"  .activation_min = {layer.activation_min},\n"
                f"  .activation_max = {layer.activation_max},\n"
                f"  .kernel_sum = {stem}_ks,\n"
                "};")
        elif isinstance(layer, AddLayer):
            stem = f"L{i}_add"
            lines.append(
                f"static const AddParams P_{stem} = {{\n"
                f"  .num_elements = {layer.num_elements}u,\n"
                f"  .self_zp = {layer.self_zp},\n"
                f"  .self_multiplier = {layer.self_multiplier},\n"
                f"  .self_shift = {layer.self_shift},\n"
                f"  .other_zp = {layer.other_zp},\n"
                f"  .other_multiplier = {layer.other_multiplier},\n"
                f"  .other_shift = {layer.other_shift},\n"
                f"  .output_zp = {layer.output_zp},\n"
                f"  .output_multiplier = {layer.output_multiplier},\n"
                f"  .output_shift = {layer.output_shift},\n"
                f"  .activation_min = {layer.activation_min},\n"
                f"  .activation_max = {layer.activation_max},\n"
                "};")
        elif isinstance(layer, FusedAttentionLayer):
            stem = f"L{i}_attn"
            lines.append(
                f"static const AttentionParams P_{stem} = {{\n"
                f"  .batch = {layer.batch}u,\n"
                f"  .seq_len = {layer.seq_len}u,\n"
                f"  .embed_dim = {layer.embed_dim}u,\n"
                f"  .q_offset = {layer.q_offset},\n"
                f"  .k_offset = {layer.k_offset},\n"
                f"  .qk_output_zp = {layer.qk_output_zp},\n"
                f"  .qk_output_multiplier = {layer.qk_output_multiplier},\n"
                f"  .qk_output_shift = {layer.qk_output_shift},\n"
                f"  .softmax_input_multiplier = {layer.softmax_input_multiplier},\n"
                f"  .softmax_input_shift = {layer.softmax_input_shift},\n"
                f"  .v_offset = {layer.v_offset},\n"
                f"  .av_output_zp = {layer.av_output_zp},\n"
                f"  .av_output_multiplier = {layer.av_output_multiplier},\n"
                f"  .av_output_shift = {layer.av_output_shift},\n"
                "};")
        elif isinstance(layer, TransposeLayer):
            stem = f"L{i}_tr"
            shape_init = ", ".join(f"{int(d)}u" for d in layer.shape) + ", 0u" * (4 - len(layer.shape))
            stride_init = ", ".join(str(int(s)) for s in layer.in_stride) + ", 0" * (4 - len(layer.in_stride))
            lines.append(
                f"static const TransposeParams P_{stem} = {{\n"
                f"  .rank = {len(layer.shape)}u,\n"
                f"  .shape = {{ {shape_init} }},\n"
                f"  .in_stride = {{ {stride_init} }},\n"
                "};")
    lines += ["", "#endif", ""]
    (out_dir / "kwt_1_params.h").write_text("\n".join(lines))


def emit_arena(out_dir: pathlib.Path, layers: list[Layer], arena_bytes: int,
               input_elements: int, output_elements: int) -> None:
    lines: list[str] = [
        "#ifndef KWT_1_ARENA_H_",
        "#define KWT_1_ARENA_H_",
        "",
        "#include <stdint.h>",
        "",
        f"#define KWT_1_ARENA_BYTES {arena_bytes}u",
        f"#define KWT_1_INPUT_NUM_ELEMENTS {input_elements}u",
        f"#define KWT_1_OUTPUT_NUM_ELEMENTS {output_elements}u",
        "#define KWT_1_SCRATCH_BYTES 0u",
        "",
    ]
    seen: set[str] = set()
    for layer in layers:
        slots: list = []
        for attr in ("input", "output", "self_in", "other_in", "q_in", "k_in", "v_in"):
            s = getattr(layer, attr, None)
            if s is not None:
                slots.append(s)
        for slot in slots:
            if slot.name in seen:
                continue
            seen.add(slot.name)
            lines.append(f"#define ACT_OFFSET_{slot.name} {slot.offset}u")
    lines += [
        "",
        "/* QuantInputParams + DequantOutputParams are tiny helpers used by",
        " * kwt_1_inference.c's stub entry/exit; they live here so the params",
        " * header can reference them. */",
        "typedef struct {",
        "  uint32_t num_elements;",
        "  float    scale;",
        "  int32_t  zero_point;",
        "  int32_t  qmin;",
        "  int32_t  qmax;",
        "} QuantInputParams;",
        "",
        "typedef struct {",
        "  uint32_t num_elements;",
        "  float    scale;",
        "  int32_t  zero_point;",
        "} DequantOutputParams;",
        "",
        "#endif",
        "",
    ]
    (out_dir / "kwt_1_arena.h").write_text("\n".join(lines))


def emit_inference_body(out_dir: pathlib.Path, layers: list[Layer]) -> None:
    """Emit a #-includable .h with the sequence of kernel calls.

    Each call site is wrapped in KWT_1_PROFILE_BEGIN/END so a -DKWT_1_PROFILE=1
    build accumulates per-kernel cycle counts.  When KWT_1_PROFILE=0 (default),
    the macros expand to no-ops and the wrapper compound statement is just
    straight-line code that the compiler folds away.
    """
    lines: list[str] = [
        "/* Auto-generated by tools/dump_kwt_1_artifacts.py.  Do not edit.",
        " * Sequence of kernel calls for one KWT-1 inference.  Caller",
        " * provides `input_float` and `output_q`; this body references",
        " * `kwt_1_arena` (extern declared in kwt_1_inference.c) and the",
        " * P_<...> param-struct constants from kwt_1_params.h. */",
        "",
    ]

    def _emit_call(idx: int, name: str, call: str) -> str:
        return (
            f"  {{ KWT_1_PROFILE_BEGIN();\n"
            f"    {call}\n"
            f"    KWT_1_PROFILE_END({idx}, \"{name}\"); }}"
        )

    for i, layer in enumerate(layers):
        if isinstance(layer, QuantInputLayer):
            call = (f"kwt_1_quantize_input(input_float, "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_quant);")
            lines.append(_emit_call(i, f"L{i}_quantize_input", call))
        elif isinstance(layer, DequantOutputLayer):
            # The runner writes the int8 model output to output_q
            # directly; the dequant is purely for caller convenience.
            call = (f"__builtin_memcpy(output_q, (int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.input.name}), "
                    f"{layer.num_elements});")
            lines.append(_emit_call(i, f"L{i}_dequant_memcpy", call))
        elif isinstance(layer, LayerNormLayer):
            call = (f"layer_norm_s8((const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.input.name}), "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_ln);")
            lines.append(_emit_call(i, f"L{i}_layer_norm", call))
        elif isinstance(layer, GELULayer):
            call = (f"gelu_lut_s8((const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.input.name}), "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_gelu);")
            lines.append(_emit_call(i, f"L{i}_gelu", call))
        elif isinstance(layer, LinearLayer):
            call = (f"linear_s8((const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.input.name}), "
                    f"L{i}_lin_w, "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_lin);")
            lines.append(_emit_call(i, f"L{i}_linear", call))
        elif isinstance(layer, AddLayer):
            call = (f"add_s8((const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.self_in.name}), "
                    f"(const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.other_in.name}), "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_add);")
            lines.append(_emit_call(i, f"L{i}_add", call))
        elif isinstance(layer, FusedAttentionLayer):
            call = (f"attention_fused_s8("
                    f"(const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.q_in.name}), "
                    f"(const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.k_in.name}), "
                    f"(const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.v_in.name}), "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_attn);")
            lines.append(_emit_call(i, f"L{i}_attention", call))
        elif isinstance(layer, TransposeLayer):
            call = (f"transpose_s8((const int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.input.name}), "
                    f"(int8_t*)(kwt_1_arena + ACT_OFFSET_{layer.output.name}), &P_L{i}_tr);")
            lines.append(_emit_call(i, f"L{i}_transpose", call))
    lines.append("")
    (out_dir / "kwt_1_inference_body.h").write_text("\n".join(lines))
