[package]
name = "run-pte"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
xnnpack = ["et-backend-ffi/xnnpack"]

[dependencies]
et-core = { workspace = true, features = ["std"] }
et-flatbuffer = { workspace = true, features = ["std"] }
et-runtime = { workspace = true, features = ["std"] }
et-kernel-ffi = { workspace = true }
et-backend-ffi = { workspace = true }
flatbuffers = { workspace = true }
