/*
 * Copyright 2026 Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Authored with assistance from Claude (claude.ai/code).
 *
 * KWT-1 inference entry point.  The body is auto-generated by
 * tools/dump_kwt_1_artifacts.py from the lowered exported program:
 * one kernel call per cortex_m op in topological order, referencing
 * arena offsets + the P_<...> param struct constants emitted into
 * kwt_1_params.h.
 */

#include <stddef.h>
#include <stdint.h>
#include <math.h>
#include <string.h>

#include "kwt_1_inference.h"
#include "kwt_1_arena.h"
#include "kwt_1_kernels.h"
#include "kwt_1_params.h"
#include "kwt_1_profile.h"

extern uint8_t kwt_1_arena[];

#if KWT_1_PROFILE
/* Storage for the per-kernel profile.  The PMU read (kwt_1_profile_now)
 * and the dump function are defined alongside the runner because
 * ARM_PMU_Get_CCNTR is a static-inline in CMSIS and not linkable. */
uint32_t kwt_1_profile_cycles[KWT_1_PROFILE_MAX_KERNELS];
const char* kwt_1_profile_names[KWT_1_PROFILE_MAX_KERNELS];
uint32_t kwt_1_profile_count;
#endif


/* Float → int8 per-tensor quantize, matching cortex_m.quantize_per_tensor.
 * Used as the model entry point: the user passes float features, we
 * quantize into the first arena slot. */
static void kwt_1_quantize_input(
    const float* input, int8_t* output, const QuantInputParams* p) {
  /* Match PyTorch's quantize_per_tensor exactly: round(x / scale) + zp.
   * Using `x / scale` rather than `x * inv_scale` avoids 1-LSB drift
   * accumulating across 17 fused-block layers. */
  for (uint32_t i = 0; i < p->num_elements; ++i) {
    float scaled = input[i] / p->scale;
    int32_t r = (int32_t)(scaled + (scaled >= 0.0f ? 0.5f : -0.5f));
    r += p->zero_point;
    if (r < p->qmin) r = p->qmin;
    if (r > p->qmax) r = p->qmax;
    output[i] = (int8_t)r;
  }
}


void kwt_1_inference(const float* input_float, int8_t* output_q) {
  /* Generated body — one kernel call per op in topological order. */
#include "kwt_1_inference_body.h"

#ifdef KWT_1_DEBUG_DUMP_OFFSET
  /* Dump a 32-byte window from any arena offset.  Set KWT_1_DEBUG_DUMP_OFFSET
   * to the offset macro of the slot you want to inspect. */
  __builtin_memcpy(output_q, (int8_t*)(kwt_1_arena + KWT_1_DEBUG_DUMP_OFFSET), 32);
#endif
}
