// Auto-generated. Do not edit.
// Body of mobilenet_v2_inference(). Variables expected from caller:
//   const float* input_float;  int8_t* output_q;
//   extern uint8_t mv2_arena[];

  quantize_input(input_float, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantize_per_tensor_default), &P_L0_quant);
  stem_dwconv2d_conv2d_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantize_per_tensor_default), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_stem_dwconv2d_conv2d_fused_default), &P_L1_sdp);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_stem_dwconv2d_conv2d_fused_default), (const int8_t*)0, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default), &P_L2_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_1), &P_L3_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_1), (const int8_t*)0, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_2), &P_L4_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_2), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_2), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_3), &P_L5_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_3), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_3), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_4), &P_L6_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_4), (const int8_t*)0, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_5), &P_L7_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_5), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_5), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_6), &P_L8_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_6), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_6), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_7), &P_L9_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_7), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_7), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_8), &P_L10_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_8), (const int8_t*)0, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_9), &P_L11_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_9), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_9), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_10), &P_L12_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_10), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_10), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_11), &P_L13_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_11), (const int8_t*)0, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_12), &P_L14_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_12), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_12), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_13), &P_L15_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_13), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_13), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_14), &P_L16_ires);
  inverted_residual_fused_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_14), (const int8_t*)0, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_15), &P_L17_ires);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_15), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_34), &P_L18_conv2d);
  avgpool_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_34), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_avg_pool2d_default), &P_L19_avgpool);
  __builtin_memcpy((void*)(mv2_arena + ACT_OFFSET_aten_view_copy_default), (const void*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_avg_pool2d_default), 1280u);
  __builtin_memcpy((void*)(mv2_arena + ACT_OFFSET_dim_order_ops__clone_dim_order_default), (const void*)(mv2_arena + ACT_OFFSET_aten_view_copy_default), 1280u);
  gemv_s8((const int8_t*)(mv2_arena + ACT_OFFSET_dim_order_ops__clone_dim_order_default), output_q, &P_L22_linear);
