// Auto-generated. Do not edit.
// Body of mobilenet_v2_inference(). Variables expected from caller:
//   const float* input_float;  int8_t* output_q;
//   extern uint8_t mv2_arena[];

  quantize_input(input_float, (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantize_per_tensor_default), &P_L0_quant);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantize_per_tensor_default), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default), &P_L1_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default), &P_L2_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_1), &P_L3_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_1), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_2), &P_L4_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_2), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_1), &P_L5_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_1), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_3), &P_L6_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_3), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_4), &P_L7_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_4), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_2), &P_L8_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_2), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_5), &P_L9_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_3), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_5), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default), &P_L10_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_6), &P_L11_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_6), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_3), &P_L12_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_3), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_7), &P_L13_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_7), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_8), &P_L14_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_8), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_4), &P_L15_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_4), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_9), &P_L16_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_7), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_9), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_1), &P_L17_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_1), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_10), &P_L18_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_10), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_5), &P_L19_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_5), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_11), &P_L20_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_1), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_11), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_2), &P_L21_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_2), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_12), &P_L22_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_12), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_6), &P_L23_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_6), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_13), &P_L24_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_13), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_14), &P_L25_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_14), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_7), &P_L26_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_7), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_15), &P_L27_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_13), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_15), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_3), &P_L28_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_3), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_16), &P_L29_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_16), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_8), &P_L30_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_8), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_17), &P_L31_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_3), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_17), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_4), &P_L32_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_4), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_18), &P_L33_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_18), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_9), &P_L34_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_9), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_19), &P_L35_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_4), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_19), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_5), &P_L36_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_5), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_20), &P_L37_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_20), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_10), &P_L38_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_10), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_21), &P_L39_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_21), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_22), &P_L40_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_22), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_11), &P_L41_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_11), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_23), &P_L42_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_21), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_23), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_6), &P_L43_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_6), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_24), &P_L44_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_24), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_12), &P_L45_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_12), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_25), &P_L46_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_6), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_25), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_7), &P_L47_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_7), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_26), &P_L48_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_26), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_13), &P_L49_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_13), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_27), &P_L50_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_27), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_28), &P_L51_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_28), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_14), &P_L52_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_14), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_29), &P_L53_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_27), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_29), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_8), &P_L54_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_8), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_30), &P_L55_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_30), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_15), &P_L56_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_15), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_31), &P_L57_conv2d);
  add_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_8), (const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_31), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_9), &P_L58_add);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_add_default_9), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_32), &P_L59_conv2d);
  dwconv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_32), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_16), &P_L60_dwconv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_depthwise_conv2d_default_16), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_33), &P_L61_conv2d);
  conv2d_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_33), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_34), &P_L62_conv2d);
  avgpool_s8((const int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_conv2d_default_34), (int8_t*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_avg_pool2d_default), &P_L63_avgpool);
  __builtin_memcpy((void*)(mv2_arena + ACT_OFFSET_aten_view_copy_default), (const void*)(mv2_arena + ACT_OFFSET_cortex_m_quantized_avg_pool2d_default), 1280u);
  __builtin_memcpy((void*)(mv2_arena + ACT_OFFSET_dim_order_ops__clone_dim_order_default), (const void*)(mv2_arena + ACT_OFFSET_aten_view_copy_default), 1280u);
  gemv_s8((const int8_t*)(mv2_arena + ACT_OFFSET_dim_order_ops__clone_dim_order_default), output_q, &P_L66_linear);
