#ifndef MV2_ARENA_H_
#define MV2_ARENA_H_

#include <stdint.h>

#define MV2_ARENA_BYTES 351232u
#define MV2_INPUT_NUM_ELEMENTS 150528u
#define MV2_OUTPUT_NUM_ELEMENTS 1000u
#define MV2_OUTPUT_SCALE 0.0209894422f
#define MV2_OUTPUT_ZERO_POINT -62
#define MV2_FUSED_SCRATCH_BYTES 38976u

#define ACT_OFFSET_cortex_m_quantize_per_tensor_default 200704u
#define ACT_OFFSET_cortex_m_quantized_stem_dwconv2d_conv2d_fused_default 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_1 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_2 75264u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_3 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_4 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_5 25088u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_6 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_7 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_8 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_9 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_10 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_11 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_12 18816u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_13 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_14 0u
#define ACT_OFFSET_cortex_m_quantized_conv2d_dwconv2d_conv2d_fused_default_15 200704u
#define ACT_OFFSET_cortex_m_quantized_conv2d_default_34 0u
#define ACT_OFFSET_cortex_m_quantized_avg_pool2d_default 62720u
#define ACT_OFFSET_aten_view_copy_default 200704u
#define ACT_OFFSET_dim_order_ops__clone_dim_order_default 0u
#define ACT_OFFSET_cortex_m_quantized_linear_default 200704u

#endif
