#ifndef MV2_PARAMS_H_
#define MV2_PARAMS_H_

#include "mv2_layer_params.h"
#include "mv2_weights.h"
#include "mv2_arena.h"

static const QuantInputParams P_L0_quant = {
  .num_elements = 150528u,
  .scale = 0.0186493322f,
  .zero_point = -14,
  .qmin = -128,
  .qmax = 127,
};
static const FusedStemDwconv2dConv2dParams P_L1_sdp = {
  .in_h = 224u, .in_w = 224u, .in_c = 3u,
  .stem_out_h = 112u, .stem_out_w = 112u,
  .stem_out_c = 32u,
  .out_h = 112u, .out_w = 112u,
  .project_out_c = 16u,
  .stem_kernel_h = 3u, .stem_kernel_w = 3u,
  .stem_stride_h = 2u, .stem_stride_w = 2u,
  .stem_pad_h = 1u, .stem_pad_w = 1u,
  .dw_kernel_h = 3u, .dw_kernel_w = 3u,
  .dw_stride_h = 1u, .dw_stride_w = 1u,
  .dw_pad_h = 1u, .dw_pad_w = 1u,
  .stem_weight = L1_sdp_stem_weight,
  .stem_weight_packed_32 = L1_sdp_stem_weight_packed_32,
  .stem_bias = L1_sdp_stem_bias,
  .stem_requant_mults = L1_sdp_stem_requant_mults,
  .stem_requant_shifts = L1_sdp_stem_requant_shifts,
  .stem_input_offset = 14,
  .stem_output_offset = -128,
  .stem_activation_min = -128,
  .stem_activation_max = 127,
  .dw_weight = L1_sdp_dw_weight,
  .dw_bias = L1_sdp_dw_bias,
  .dw_bias_with_offset_full = L1_sdp_dw_bias_off,
  .dw_requant_mults = L1_sdp_dw_requant_mults,
  .dw_requant_shifts = L1_sdp_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L1_sdp_project_weight,
  .project_bias = L1_sdp_project_bias,
  .project_requant_mults = L1_sdp_project_requant_mults,
  .project_requant_shifts = L1_sdp_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 19,
  .project_activation_min = -128,
  .project_activation_max = 127,
};
static const FusedInvertedResidualParams P_L2_ires = {
  .in_h = 112u, .in_w = 112u, .in_c = 16u,
  .expand_out_c = 96u,
  .dw_out_h = 56u, .dw_out_w = 56u,
  .out_h = 56u, .out_w = 56u,
  .project_out_c = 24u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 2u, .stride_w = 2u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L2_ires_expand_weight,
  .expand_bias = L2_ires_expand_bias,
  .expand_requant_mults = L2_ires_expand_requant_mults,
  .expand_requant_shifts = L2_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L2_ires_dw_weight,
  .dw_bias = L2_ires_dw_bias,
  .dw_bias_with_offset_full = L2_ires_dw_bias_off,
  .dw_requant_mults = L2_ires_dw_requant_mults,
  .dw_requant_shifts = L2_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L2_ires_project_weight,
  .project_bias = L2_ires_project_bias,
  .project_requant_mults = L2_ires_project_requant_mults,
  .project_requant_shifts = L2_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 1,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 0,
  .residual_self_zero_point = 0,
  .residual_self_multiplier = 0,
  .residual_self_shift = 0,
  .residual_other_zero_point = 0,
  .residual_other_multiplier = 0,
  .residual_other_shift = 0,
  .residual_output_zero_point = 0,
  .residual_output_multiplier = 0,
  .residual_output_shift = 0,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L3_ires = {
  .in_h = 56u, .in_w = 56u, .in_c = 24u,
  .expand_out_c = 144u,
  .dw_out_h = 56u, .dw_out_w = 56u,
  .out_h = 56u, .out_w = 56u,
  .project_out_c = 24u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L3_ires_expand_weight,
  .expand_bias = L3_ires_expand_bias,
  .expand_requant_mults = L3_ires_expand_requant_mults,
  .expand_requant_shifts = L3_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L3_ires_dw_weight,
  .dw_bias = L3_ires_dw_bias,
  .dw_bias_with_offset_full = L3_ires_dw_bias_off,
  .dw_requant_mults = L3_ires_dw_requant_mults,
  .dw_requant_shifts = L3_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L3_ires_project_weight,
  .project_bias = L3_ires_project_bias,
  .project_requant_mults = L3_ires_project_requant_mults,
  .project_requant_shifts = L3_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -3,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = -3,
  .residual_self_multiplier = 2136286480,
  .residual_self_shift = -1,
  .residual_other_zero_point = 1,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = 4,
  .residual_output_multiplier = 2084783180,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L4_ires = {
  .in_h = 56u, .in_w = 56u, .in_c = 24u,
  .expand_out_c = 144u,
  .dw_out_h = 28u, .dw_out_w = 28u,
  .out_h = 28u, .out_w = 28u,
  .project_out_c = 32u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 2u, .stride_w = 2u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L4_ires_expand_weight,
  .expand_bias = L4_ires_expand_bias,
  .expand_requant_mults = L4_ires_expand_requant_mults,
  .expand_requant_shifts = L4_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L4_ires_dw_weight,
  .dw_bias = L4_ires_dw_bias,
  .dw_bias_with_offset_full = L4_ires_dw_bias_off,
  .dw_requant_mults = L4_ires_dw_requant_mults,
  .dw_requant_shifts = L4_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L4_ires_project_weight,
  .project_bias = L4_ires_project_bias,
  .project_requant_mults = L4_ires_project_requant_mults,
  .project_requant_shifts = L4_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -8,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 0,
  .residual_self_zero_point = 0,
  .residual_self_multiplier = 0,
  .residual_self_shift = 0,
  .residual_other_zero_point = 0,
  .residual_other_multiplier = 0,
  .residual_other_shift = 0,
  .residual_output_zero_point = 0,
  .residual_output_multiplier = 0,
  .residual_output_shift = 0,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L5_ires = {
  .in_h = 28u, .in_w = 28u, .in_c = 32u,
  .expand_out_c = 192u,
  .dw_out_h = 28u, .dw_out_w = 28u,
  .out_h = 28u, .out_w = 28u,
  .project_out_c = 32u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L5_ires_expand_weight,
  .expand_bias = L5_ires_expand_bias,
  .expand_requant_mults = L5_ires_expand_requant_mults,
  .expand_requant_shifts = L5_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L5_ires_dw_weight,
  .dw_bias = L5_ires_dw_bias,
  .dw_bias_with_offset_full = L5_ires_dw_bias_off,
  .dw_requant_mults = L5_ires_dw_requant_mults,
  .dw_requant_shifts = L5_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L5_ires_project_weight,
  .project_bias = L5_ires_project_bias,
  .project_requant_mults = L5_ires_project_requant_mults,
  .project_requant_shifts = L5_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -11,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = -11,
  .residual_self_multiplier = 2073398174,
  .residual_self_shift = -1,
  .residual_other_zero_point = -8,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = 5,
  .residual_output_multiplier = 1864441030,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L6_ires = {
  .in_h = 28u, .in_w = 28u, .in_c = 32u,
  .expand_out_c = 192u,
  .dw_out_h = 28u, .dw_out_w = 28u,
  .out_h = 28u, .out_w = 28u,
  .project_out_c = 32u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L6_ires_expand_weight,
  .expand_bias = L6_ires_expand_bias,
  .expand_requant_mults = L6_ires_expand_requant_mults,
  .expand_requant_shifts = L6_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L6_ires_dw_weight,
  .dw_bias = L6_ires_dw_bias,
  .dw_bias_with_offset_full = L6_ires_dw_bias_off,
  .dw_requant_mults = L6_ires_dw_requant_mults,
  .dw_requant_shifts = L6_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L6_ires_project_weight,
  .project_bias = L6_ires_project_bias,
  .project_requant_mults = L6_ires_project_requant_mults,
  .project_requant_shifts = L6_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 48,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = 48,
  .residual_self_multiplier = 1073741824,
  .residual_self_shift = 0,
  .residual_other_zero_point = 5,
  .residual_other_multiplier = 2075465084,
  .residual_other_shift = -1,
  .residual_output_zero_point = 12,
  .residual_output_multiplier = 1868478324,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L7_ires = {
  .in_h = 28u, .in_w = 28u, .in_c = 32u,
  .expand_out_c = 192u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 64u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 2u, .stride_w = 2u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L7_ires_expand_weight,
  .expand_bias = L7_ires_expand_bias,
  .expand_requant_mults = L7_ires_expand_requant_mults,
  .expand_requant_shifts = L7_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L7_ires_dw_weight,
  .dw_bias = L7_ires_dw_bias,
  .dw_bias_with_offset_full = L7_ires_dw_bias_off,
  .dw_requant_mults = L7_ires_dw_requant_mults,
  .dw_requant_shifts = L7_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L7_ires_project_weight,
  .project_bias = L7_ires_project_bias,
  .project_requant_mults = L7_ires_project_requant_mults,
  .project_requant_shifts = L7_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -6,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 0,
  .residual_self_zero_point = 0,
  .residual_self_multiplier = 0,
  .residual_self_shift = 0,
  .residual_other_zero_point = 0,
  .residual_other_multiplier = 0,
  .residual_other_shift = 0,
  .residual_output_zero_point = 0,
  .residual_output_multiplier = 0,
  .residual_output_shift = 0,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L8_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 64u,
  .expand_out_c = 384u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 64u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L8_ires_expand_weight,
  .expand_bias = L8_ires_expand_bias,
  .expand_requant_mults = L8_ires_expand_requant_mults,
  .expand_requant_shifts = L8_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L8_ires_dw_weight,
  .dw_bias = L8_ires_dw_bias,
  .dw_bias_with_offset_full = L8_ires_dw_bias_off,
  .dw_requant_mults = L8_ires_dw_requant_mults,
  .dw_requant_shifts = L8_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L8_ires_project_weight,
  .project_bias = L8_ires_project_bias,
  .project_requant_mults = L8_ires_project_requant_mults,
  .project_requant_shifts = L8_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -5,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = -5,
  .residual_self_multiplier = 1073741824,
  .residual_self_shift = 0,
  .residual_other_zero_point = -6,
  .residual_other_multiplier = 1861884347,
  .residual_other_shift = -1,
  .residual_output_zero_point = -12,
  .residual_output_multiplier = 1994974720,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L9_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 64u,
  .expand_out_c = 384u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 64u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L9_ires_expand_weight,
  .expand_bias = L9_ires_expand_bias,
  .expand_requant_mults = L9_ires_expand_requant_mults,
  .expand_requant_shifts = L9_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L9_ires_dw_weight,
  .dw_bias = L9_ires_dw_bias,
  .dw_bias_with_offset_full = L9_ires_dw_bias_off,
  .dw_requant_mults = L9_ires_dw_requant_mults,
  .dw_requant_shifts = L9_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L9_ires_project_weight,
  .project_bias = L9_ires_project_bias,
  .project_requant_mults = L9_ires_project_requant_mults,
  .project_requant_shifts = L9_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 5,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = 5,
  .residual_self_multiplier = 1406142050,
  .residual_self_shift = -1,
  .residual_other_zero_point = -12,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = -13,
  .residual_output_multiplier = 1143143277,
  .residual_output_shift = -18,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L10_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 64u,
  .expand_out_c = 384u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 64u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L10_ires_expand_weight,
  .expand_bias = L10_ires_expand_bias,
  .expand_requant_mults = L10_ires_expand_requant_mults,
  .expand_requant_shifts = L10_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L10_ires_dw_weight,
  .dw_bias = L10_ires_dw_bias,
  .dw_bias_with_offset_full = L10_ires_dw_bias_off,
  .dw_requant_mults = L10_ires_dw_requant_mults,
  .dw_requant_shifts = L10_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L10_ires_project_weight,
  .project_bias = L10_ires_project_bias,
  .project_requant_mults = L10_ires_project_requant_mults,
  .project_requant_shifts = L10_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -14,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = -14,
  .residual_self_multiplier = 2069320760,
  .residual_self_shift = -1,
  .residual_other_zero_point = -13,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = -25,
  .residual_output_multiplier = 1801450652,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L11_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 64u,
  .expand_out_c = 384u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 96u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L11_ires_expand_weight,
  .expand_bias = L11_ires_expand_bias,
  .expand_requant_mults = L11_ires_expand_requant_mults,
  .expand_requant_shifts = L11_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L11_ires_dw_weight,
  .dw_bias = L11_ires_dw_bias,
  .dw_bias_with_offset_full = L11_ires_dw_bias_off,
  .dw_requant_mults = L11_ires_dw_requant_mults,
  .dw_requant_shifts = L11_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L11_ires_project_weight,
  .project_bias = L11_ires_project_bias,
  .project_requant_mults = L11_ires_project_requant_mults,
  .project_requant_shifts = L11_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 4,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 0,
  .residual_self_zero_point = 0,
  .residual_self_multiplier = 0,
  .residual_self_shift = 0,
  .residual_other_zero_point = 0,
  .residual_other_multiplier = 0,
  .residual_other_shift = 0,
  .residual_output_zero_point = 0,
  .residual_output_multiplier = 0,
  .residual_output_shift = 0,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L12_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 96u,
  .expand_out_c = 576u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 96u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L12_ires_expand_weight,
  .expand_bias = L12_ires_expand_bias,
  .expand_requant_mults = L12_ires_expand_requant_mults,
  .expand_requant_shifts = L12_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L12_ires_dw_weight,
  .dw_bias = L12_ires_dw_bias,
  .dw_bias_with_offset_full = L12_ires_dw_bias_off,
  .dw_requant_mults = L12_ires_dw_requant_mults,
  .dw_requant_shifts = L12_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L12_ires_project_weight,
  .project_bias = L12_ires_project_bias,
  .project_requant_mults = L12_ires_project_requant_mults,
  .project_requant_shifts = L12_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 5,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = 5,
  .residual_self_multiplier = 1505829477,
  .residual_self_shift = -1,
  .residual_other_zero_point = 4,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = 8,
  .residual_output_multiplier = 1855937379,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L13_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 96u,
  .expand_out_c = 576u,
  .dw_out_h = 14u, .dw_out_w = 14u,
  .out_h = 14u, .out_w = 14u,
  .project_out_c = 96u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L13_ires_expand_weight,
  .expand_bias = L13_ires_expand_bias,
  .expand_requant_mults = L13_ires_expand_requant_mults,
  .expand_requant_shifts = L13_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L13_ires_dw_weight,
  .dw_bias = L13_ires_dw_bias,
  .dw_bias_with_offset_full = L13_ires_dw_bias_off,
  .dw_requant_mults = L13_ires_dw_requant_mults,
  .dw_requant_shifts = L13_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L13_ires_project_weight,
  .project_bias = L13_ires_project_bias,
  .project_requant_mults = L13_ires_project_requant_mults,
  .project_requant_shifts = L13_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 16,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = 16,
  .residual_self_multiplier = 1551646642,
  .residual_self_shift = -1,
  .residual_other_zero_point = 8,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = -1,
  .residual_output_multiplier = 1820789426,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L14_ires = {
  .in_h = 14u, .in_w = 14u, .in_c = 96u,
  .expand_out_c = 576u,
  .dw_out_h = 7u, .dw_out_w = 7u,
  .out_h = 7u, .out_w = 7u,
  .project_out_c = 160u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 2u, .stride_w = 2u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L14_ires_expand_weight,
  .expand_bias = L14_ires_expand_bias,
  .expand_requant_mults = L14_ires_expand_requant_mults,
  .expand_requant_shifts = L14_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L14_ires_dw_weight,
  .dw_bias = L14_ires_dw_bias,
  .dw_bias_with_offset_full = L14_ires_dw_bias_off,
  .dw_requant_mults = L14_ires_dw_requant_mults,
  .dw_requant_shifts = L14_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L14_ires_project_weight,
  .project_bias = L14_ires_project_bias,
  .project_requant_mults = L14_ires_project_requant_mults,
  .project_requant_shifts = L14_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -2,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 0,
  .residual_self_zero_point = 0,
  .residual_self_multiplier = 0,
  .residual_self_shift = 0,
  .residual_other_zero_point = 0,
  .residual_other_multiplier = 0,
  .residual_other_shift = 0,
  .residual_output_zero_point = 0,
  .residual_output_multiplier = 0,
  .residual_output_shift = 0,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L15_ires = {
  .in_h = 7u, .in_w = 7u, .in_c = 160u,
  .expand_out_c = 960u,
  .dw_out_h = 7u, .dw_out_w = 7u,
  .out_h = 7u, .out_w = 7u,
  .project_out_c = 160u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L15_ires_expand_weight,
  .expand_bias = L15_ires_expand_bias,
  .expand_requant_mults = L15_ires_expand_requant_mults,
  .expand_requant_shifts = L15_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L15_ires_dw_weight,
  .dw_bias = L15_ires_dw_bias,
  .dw_bias_with_offset_full = L15_ires_dw_bias_off,
  .dw_requant_mults = L15_ires_dw_requant_mults,
  .dw_requant_shifts = L15_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L15_ires_project_weight,
  .project_bias = L15_ires_project_bias,
  .project_requant_mults = L15_ires_project_requant_mults,
  .project_requant_shifts = L15_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 4,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = 4,
  .residual_self_multiplier = 1073741824,
  .residual_self_shift = 0,
  .residual_other_zero_point = -2,
  .residual_other_multiplier = 1377748639,
  .residual_other_shift = -1,
  .residual_output_zero_point = 25,
  .residual_output_multiplier = 1898834565,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L16_ires = {
  .in_h = 7u, .in_w = 7u, .in_c = 160u,
  .expand_out_c = 960u,
  .dw_out_h = 7u, .dw_out_w = 7u,
  .out_h = 7u, .out_w = 7u,
  .project_out_c = 160u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L16_ires_expand_weight,
  .expand_bias = L16_ires_expand_bias,
  .expand_requant_mults = L16_ires_expand_requant_mults,
  .expand_requant_shifts = L16_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L16_ires_dw_weight,
  .dw_bias = L16_ires_dw_bias,
  .dw_bias_with_offset_full = L16_ires_dw_bias_off,
  .dw_requant_mults = L16_ires_dw_requant_mults,
  .dw_requant_shifts = L16_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L16_ires_project_weight,
  .project_bias = L16_ires_project_bias,
  .project_requant_mults = L16_ires_project_requant_mults,
  .project_requant_shifts = L16_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = 2,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 1,
  .residual_self_zero_point = 2,
  .residual_self_multiplier = 1696048611,
  .residual_self_shift = -1,
  .residual_other_zero_point = 25,
  .residual_other_multiplier = 1073741824,
  .residual_other_shift = 0,
  .residual_output_zero_point = 10,
  .residual_output_multiplier = 1439936412,
  .residual_output_shift = -19,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const FusedInvertedResidualParams P_L17_ires = {
  .in_h = 7u, .in_w = 7u, .in_c = 160u,
  .expand_out_c = 960u,
  .dw_out_h = 7u, .dw_out_w = 7u,
  .out_h = 7u, .out_w = 7u,
  .project_out_c = 320u,
  .kernel_h = 3u, .kernel_w = 3u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 1u, .pad_w = 1u,
  .expand_weight = L17_ires_expand_weight,
  .expand_bias = L17_ires_expand_bias,
  .expand_requant_mults = L17_ires_expand_requant_mults,
  .expand_requant_shifts = L17_ires_expand_requant_shifts,
  .expand_input_offset = 0,
  .expand_output_offset = -128,
  .expand_activation_min = -128,
  .expand_activation_max = 127,
  .dw_weight = L17_ires_dw_weight,
  .dw_bias = L17_ires_dw_bias,
  .dw_bias_with_offset_full = L17_ires_dw_bias_off,
  .dw_requant_mults = L17_ires_dw_requant_mults,
  .dw_requant_shifts = L17_ires_dw_requant_shifts,
  .dw_input_offset = 128,
  .dw_output_offset = -128,
  .dw_activation_min = -128,
  .dw_activation_max = 127,
  .project_weight = L17_ires_project_weight,
  .project_bias = L17_ires_project_bias,
  .project_requant_mults = L17_ires_project_requant_mults,
  .project_requant_shifts = L17_ires_project_requant_shifts,
  .project_input_offset = 0,
  .project_output_offset = -1,
  .project_activation_min = -128,
  .project_activation_max = 127,
  .residual_present = 0,
  .residual_self_zero_point = 0,
  .residual_self_multiplier = 0,
  .residual_self_shift = 0,
  .residual_other_zero_point = 0,
  .residual_other_multiplier = 0,
  .residual_other_shift = 0,
  .residual_output_zero_point = 0,
  .residual_output_multiplier = 0,
  .residual_output_shift = 0,
  .residual_activation_min = -128,
  .residual_activation_max = 127,
};
static const Conv2dParams P_L18_conv2d = {
  .in_h = 7u, .in_w = 7u, .in_c = 320u,
  .out_h = 7u, .out_w = 7u, .out_c = 1280u,
  .kernel_h = 1u, .kernel_w = 1u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 0u, .pad_w = 0u,
  .weight = L18_conv2d_weight,
  .bias = L18_conv2d_bias,
  .requant_mults = L18_conv2d_requant_mults,
  .requant_shifts = L18_conv2d_requant_shifts,
  .input_offset = 0,
  .output_offset = -128,
  .activation_min = -128,
  .activation_max = 127,
  .weight_packed_32 = (const int8_t*)0,
};
static const AvgPool2dParams P_L19_avgpool = {
  .in_h = 7u, .in_w = 7u, .channels = 1280u,
  .out_h = 1u, .out_w = 1u,
  .kernel_h = 7u, .kernel_w = 7u,
  .stride_h = 1u, .stride_w = 1u,
  .pad_h = 0u, .pad_w = 0u,
  .zero_point = -128,
  .multiplier = 1578242560,
  .shift = -5,
};
static const LinearParams P_L22_linear = {
  .in_features = 1280u,
  .out_features = 1000u,
  .weight = L22_linear_weight,
  .bias = (const int32_t*)0,
  .kernel_sum = L22_linear_kernel_sum,
  .input_offset = 128,
  .filter_offset = 0,
  .output_offset = -62,
  .multiplier = 1177044262,
  .shift = -7,
  .activation_min = -128,
  .activation_max = 127,
};

#endif
